; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
	bblanchon/ArduinoJson@^7.2.2
build_flags = 
	-D ENV_TEENSY
	-I$PROJECT_DIR/src/hardware
	-I$PROJECT_DIR/src/modules
build_src_filter = 
	+<*>
	-<hardware/**/fake_*>

[env:test]
platform = native
test_framework = unity
lib_deps = 
	throwtheswitch/Unity @ ^2.6.1
	bblanchon/ArduinoJson@^7.2.2
build_flags = 
	-DUNIT_TEST
	-D ENV_FAKE
	-D ENV_TEST
	-I$PROJECT_DIR/src/hardware
	-I$PROJECT_DIR/src/modules
test_build_src = true
build_src_filter = 
	+<*>
	-<main.cpp>
	-<hardware/**/real_*>

[env:simulate]
platform = native
build_flags = 
	-DUNIT_TEST
	-D ENV_FAKE
	-D ENV_SIMULATE
	-I$PROJECT_DIR/src/hardware
	-I$PROJECT_DIR/src/modules
build_src_filter = 
	+<*>
	-<hardware/**/real_*>
lib_deps = bblanchon/ArduinoJson@^7.2.2
